import Navbar from './component/navbar/navbar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'The Pokedex',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={inter.className}>
        <Navbar />
        <div className='mx-4 mt-11 lg:mx-28'>
          {children}
        </div>
      </body>
    </html>
  )
}